---
# defaults file for install-ckan

apt_requirements:
  - python-apt
  - python-dev
  - postgresql
  - libpq-dev
  - python-pip
  - python-virtualenv
  - git-core
  - solr-jetty
  - openjdk-8-jdk
  - redis-server
  - python-psycopg2

virtual_env: /usr/lib/ckan/default
