---
# handlers file for install-ckan

- name: Start Postgresql
  service:
    name: postgresql
    state: started

- name: Restart Jetty
  service:
    name: jetty9
    state: restarted
  become: yes
