version: 2
jobs:
  build:
    docker:
      - image: ubuntu:18.04

    steps:
      - run:
          name: Install required packages
          command: apt-get update && apt-get -y install git python-pip sudo

      - run:
          name: Upgrade pip
          command: pip install --upgrade pip

      - run:
          name: Install ansible
          command: pip install ansible

      - run:
          name: Checkout ckan
          command: git clone https://github.com/ckan/ckan.git ckan

      - checkout:
          path: ckan/CKAN-in-Vagrant

      - run:
          name: Run ansible
          command: ansible-playbook -v -i inventories/build playbook.yml
          working_directory: ~/project/ckan/CKAN-in-Vagrant

      - run: |
          /usr/lib/ckan/default/bin/paster serve /etc/ckan/default/development.ini &
          curl --fail localhost:5000
          curl --fail localhost:8983/solr/
          exec 3<>/dev/tcp/127.0.0.1/6379 && echo -e "PING\r\n" >&3 && head -c 7 <&3
