version: 2
jobs:
  build:
    docker:
      - image: ubuntu:18.04

    steps:
      - run:
          name: Checkout ckan
          command: git clone https://github.com/ckan/ckan.git ckan

      - checkout:
          path: ckan/CKAN-in-Vagrant
         
