version: 2
jobs:
  build:
    docker:
      - image: ubuntu:18.04

    steps:
      - run:
          name: Install required packages
          command: apt-get update && apt-get -y install git python-pip

      - run:
          name: Upgrade pip
          command: pip install --upgrade pip

      - run:
          name: Install ansible
          command: pip install ansible

      - run:
          name: Checkout ckan
          command: git clone https://github.com/ckan/ckan.git ckan

      - checkout:
          path: ckan/CKAN-in-Vagrant

      - run:
          name: Run ansible
          command: ansible-playbook -v ckan/CKAN-in-Vagrant/playbook.yml
