---
# tasks file for install-ckan

- name: Install apt requirements
  apt:
    pkg:
      "{{ apt_requirements }}"
  become: yes

- name: Install local ckan to virtual environment
  pip:
    name: "{{ ckan_source_path }}"
    virtualenv: "{{ virtual_env }}"
  become: yes

- name: Install ckan requirements
  pip:
    requirements: "{{ ckan_source_path }}/requirements.txt"
    virtualenv: "{{ virtual_env }}"
  become: yes

- name: Install ckan dev requirements
  pip:
    requirements: "{{ ckan_source_path }}/dev-requirements.txt"
    virtualenv: "{{ virtual_env }}"
  become: yes
