---
# tasks file for install-ckan

- name: Install apt requirements
  apt:
    pkg:
      "{{ apt_requirements }}"
  become: yes
  notify: Start Postgresql

- name: Install local ckan to virtual environment
  pip:
    name: "{{ ckan_source_path }}"
    virtualenv: "{{ virtual_env }}"
  become: yes

- name: Install ckan requirements
  pip:
    requirements: "{{ ckan_source_path }}/requirements-py2.txt"
    virtualenv: "{{ virtual_env }}"
  become: yes

- name: Install ckan dev requirements
  pip:
    requirements: "{{ ckan_source_path }}/dev-requirements.txt"
    virtualenv: "{{ virtual_env }}"
  become: yes

- meta: flush_handlers

- name: Create databases
  postgresql_db:
    name: "{{ item }}"
  with_items:
    - ckan_default
    - ckan_test
  become: yes
  become_user: postgres

- name: Create Postgres users
  postgresql_user:
    db: "{{ item }}"
    user: "{{ item }}"
    password: pass
  with_items:
    - ckan_default
    - ckan_test
  become: yes
  become_user: postgres

